### ISSUE TITLE
Safari не может найти сервер

### ISSUE THREAD

**Issue by uchvru** [slamhobb/badbalance#10]
Safari не может открыть страницу «https://badbalance.pro», так как Safari не удается найти сервер «badbalance.pro».

![2018-04-05 23 38 13](https://user-images.githubusercontent.com/13187730/38390746-e0d7eaa0-392a-11e8-825e-21ea251e43c0.png)

**Comment by uchvru** [comment]
Версия Safari 11.1 (13605.1.33.1.2)

**Comment by uchvru** [comment]
<img width="615" alt="2018-04-06 7 39 00" src="https://user-images.githubusercontent.com/13187730/38403663-c61f1588-396d-11e8-83fa-0aeba956c442.png">

Google Chrome
Версия 65.0.3325.181 (Официальная сборка), (64 бит)

**Comment by slamhobb** [comment]
Временные неполадки
