### ISSUE TITLE
Добавить сумму доходов

### ISSUE THREAD

**Issue by uchvru** [slamhobb/badbalance#12]
Необходимо добавить сумму доходов общую, так как не понятно сколько было доходов по общей сумме за месяц, приходиться считать руками, не удобно.

![image](https://user-images.githubusercontent.com/13187730/39042011-895eaa70-4492-11e8-9ec0-1277a1b1f28d.png)

**Comment by slamhobb** [comment]
Поправлю в ближайшее время

**Comment by slamhobb** [comment]
Добавлено
