### ISSUE TITLE
При добавлении новой строки, старое значение не убирается, остается в форме.

### ISSUE THREAD

**Issue by uchvru** [slamhobb/badbalance#13]
На вкладке Доходы, при добавлении новой строки (записи), старое значение не убирается, остается в форме.

![image](https://user-images.githubusercontent.com/13187730/39042358-4231a444-4493-11e8-9395-45c0c3a9a93a.png)

**Comment by slamhobb** [comment]
Поправим в ближайшее время

**Comment by slamhobb** [comment]
Исправлено
