### ISSUE TITLE
Исправить орфографическую ошибку и год

### ISSUE THREAD

**Issue by uchvru** [slamhobb/badbalance#15]
Необходимо поправить орфографическую ошибку на главной странице https://badbalance.pro 
и на /spending/, category/, /statistic/ 
год на 2018  и  "Плохой баланс" поменять буквы местами "с" и "н".

![image](https://user-images.githubusercontent.com/13187730/39043182-6468511e-4495-11e8-9cec-06d44bdf74a1.png)

![image](https://user-images.githubusercontent.com/13187730/39043224-8161c728-4495-11e8-8b9f-117b1d6c7a70.png)

**Comment by slamhobb** [comment]
Обновил
