### ISSUE TITLE
Не корректно отображается сайт через Яндекс Браузер Версия 18.3.1.1232

### ISSUE THREAD

**Issue by uchvru** [slamhobb/badbalance#16]
Не корректно отображается сайт https://badbalance.pro через Яндекс Браузер  Версия 18.3.1.1232

Страница: https://badbalance.pro/spending/ 
![2018-04-24 09-40-01](https://user-images.githubusercontent.com/13187730/39171448-87eb4212-47a7-11e8-99b5-5c780c9ad2eb.png)
Страница: https://badbalance.pro
![2018-04-24 09-38-08](https://user-images.githubusercontent.com/13187730/39171449-880b64de-47a7-11e8-9956-0d4f79785c2d.png)

**Comment by slamhobb** [comment]
Это не из Яндекс барузер, а из-за того что файлы в кеше браузера не обновились, нужно нажать ctrl+f5 и всё будет ок
