### ISSUE TITLE
Пропал список категорий badbalance.pro/category/

### ISSUE THREAD

**Issue by uchvru** [slamhobb/badbalance#17]
Пропал список категорий badbalance.pro/category/

![2018-04-27 23 27 06](https://user-images.githubusercontent.com/13187730/39384487-858ae4a2-4a5c-11e8-9e28-0944f87a839c.png)

В списках в расходах есть, точнее отображается:
<img width="1212" alt="2018-04-27 23 31 58" src="https://user-images.githubusercontent.com/13187730/39384488-85f6553e-4a5c-11e8-919e-f7a54c2407c0.png">

При добавлении новой категории, записывается и отображается:
![2018-04-27 23 34 11](https://user-images.githubusercontent.com/13187730/39384492-865ffc96-4a5c-11e8-8653-2766b4127e6f.png)
<img width="1211" alt="2018-04-27 23 35 20" src="https://user-images.githubusercontent.com/13187730/39384494-86b49ad0-4a5c-11e8-8da5-cd76433ae413.png">

<img width="396" alt="2018-04-28 0 01 16" src="https://user-images.githubusercontent.com/13187730/39385043-63cdbd4c-4a5e-11e8-814f-89adddcf7605.png">

в Хроме тоже отсуствуют категории:
<img width="1339" alt="2018-04-28 0 07 51" src="https://user-images.githubusercontent.com/13187730/39385202-2315f3d6-4a5f-11e8-8548-e21f94685c1a.png">

<img width="710" alt="2018-04-28 0 09 49" src="https://user-images.githubusercontent.com/13187730/39385263-5e73bf1c-4a5f-11e8-8ad1-0bdc1dee0ead.png">

**Comment by uchinin** [comment]
![Uploading Снимок экрана 2018-04-27 в 23.31.58.png…]()
![Uploading Снимок экрана 2018-04-27 в 23.34.11.png…]()

**Comment by slamhobb** [comment]
не воспроизводится
