### ISSUE TITLE
При добавлении новой строки в "Категориях", старое значение не убирается, остается в форме.

### ISSUE THREAD

**Issue by uchvru** [slamhobb/badbalance#18]
При добавлении новой строки в "Категориях", старое значение не убирается, остается в форме. Аналогично  Issue #13

![2018-04-27 23 34 11](https://user-images.githubusercontent.com/13187730/39384780-728d7382-4a5d-11e8-9ee0-e398706481a7.png)
<img width="1211" alt="2018-04-27 23 35 20" src="https://user-images.githubusercontent.com/13187730/39384781-72fc5b12-4a5d-11e8-8fda-646a759945ec.png">

<img width="396" alt="2018-04-28 0 01 16" src="https://user-images.githubusercontent.com/13187730/39385027-512df490-4a5e-11e8-8b60-3bd0a576983b.png">

**Comment by slamhobb** [comment]
Исправлено
