### ISSUE TITLE
Неверно названо поле "Наименование категории", указано сумма.

### ISSUE THREAD

**Issue by uchvru** [slamhobb/badbalance#2]
При переходе на вкладку "Категория" и при создании новой категории в поле "Наименование категории" указана "Сумма", необходимо переименовать значение поля.

![image](https://user-images.githubusercontent.com/13187730/32326168-e8988f22-bfe2-11e7-8476-8548f7fd4121.png)

**Comment by slamhobb** [comment]
Исправлено
