### ISSUE TITLE
Добавить информацию из Доходы на главный экран как Расходы.

### ISSUE THREAD

**Issue by uchvru** [slamhobb/badbalance#4]
Возможно добавить информацию из "Доходы" на главный экран как "Расходы".
Для удобства пользователей.

![image](https://user-images.githubusercontent.com/13187730/32326973-e6b49d60-bfe5-11e7-96be-831ccf42072c.png)

**Comment by uchvru** [comment]
А лучше вынести эту информацию в шапку сайта, за пределы вкладок.

![image](https://user-images.githubusercontent.com/13187730/32327197-b9e704e8-bfe6-11e7-8f8c-78a7ef77a2bf.png)

**Comment by slamhobb** [comment]
Добавлено
