### ISSUE TITLE
Срок действия этого сертификата уже истек или еще не наступил.

### ISSUE THREAD

**Issue by uchvru** [slamhobb/badbalance#9]
Срок действия этого сертификата уже истек или еще не наступил.

![screenshot_1](https://user-images.githubusercontent.com/13187730/34144489-c943184c-e4a2-11e7-8155-cb7372b0bdf2.png)
![screenshot_2](https://user-images.githubusercontent.com/13187730/34144490-c9636a34-e4a2-11e7-9842-50273e7a2371.png)

**Comment by slamhobb** [comment]
Обновил сертификат
